/**
 * Seed Test Listing Script
 * Creates realistic test listings with Unsplash images
 */

import { createClient } from '@supabase/supabase-js'
import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

// Get current file's directory (ESM workaround)
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Load environment variables from parent directory
dotenv.config({ path: path.join(__dirname, '../.env.local') })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

console.log('🔍 Debug - Environment check:')
console.log('   SUPABASE_URL:', supabaseUrl ? '✅ Found' : '❌ Missing')
console.log('   SERVICE_ROLE_KEY:', supabaseServiceKey ? '✅ Found' : '❌ Missing')
console.log('')

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('❌ Missing Supabase credentials')
  console.error('   Make sure .env.local exists in benalsam-web-next/')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

// ============================================================================
// UNSPLASH IMAGE FETCHER (via Edge Function)
// ============================================================================

async function fetchUnsplashImage(keyword: string): Promise<string> {
  try {
    console.log(`   🔍 Searching Unsplash for: "${keyword}"`)
    
    // Call Supabase Edge Function
    const { data, error } = await supabase.functions.invoke('fetch-unsplash-images', {
      body: { query: keyword }
    })

    if (error) {
      console.error('   ❌ Edge function error:', error)
      throw error
    }

    if (data?.images && data.images.length > 0) {
      const imageUrl = data.images[0].urls.regular
      console.log(`   ✅ Found image: ${imageUrl}`)
      return imageUrl
    }

    // Fallback to source.unsplash.com
    console.warn('   ⚠️ No images found, using fallback')
    return `https://source.unsplash.com/800x600/?${keyword}`
  } catch (error) {
    console.error('   ❌ Failed to fetch Unsplash image:', error)
    return `https://source.unsplash.com/800x600/?${keyword}`
  }
}

// ============================================================================
// TEST LISTING DATA
// ============================================================================

const USER_IDS = [
  '19a6dcfc-5f3a-494e-ad98-02bcfb135462',
  '3b098846-d952-4ef5-b250-df2b31d0eb15',
  '4d76d17f-b78e-4bc6-a779-0a3eb14ee826',
  '6417b4a3-021b-4649-a83f-a3c9ccbaf522',
  '96d5ffce-6fdc-466c-8b05-a0d8cbf5dc8d',
  'dff1eb99-c85e-49e8-81af-2ba72dd54c2b',
  'e9ae9253-752a-4abe-b0c9-0ee92f81e9c9',
]

const TEST_LISTING = {
  title: 'iPhone 15 Pro Max 256GB Mavi arıyorum [TEST]',
  description: `iPhone 15 Pro Max arıyorum. Tercihen mavi renk, 256GB veya daha fazla hafıza.

Beklentilerim:
- Kutu ve aksesuarlarıyla birlikte
- Ekran ve kasada çizik olmaması
- Garantili olması (Apple Store veya yetkili satıcı)
- Faturalı olması

Bütçem: 60.000₺'ye kadar esnek
Lokasyon: İzmir (Karşıyaka, Bornova, Konak çevresi)
Ödeme: Nakit veya havale

Not: Ciddi satıcılar lütfen fotoğraflarla birlikte teklif versin.

⚠️ BU BİR TEST İLANIDIR`,
  category_id: 502, // Elektronik > Telefon > Akıllı Telefon > Akıllı Telefonlar
  budget: 60000,
  location: 'Karşıyaka, İzmir',
  urgency: 'urgent',
  contact_preference: 'both',
  attributes: {
    brand: ['Apple'],
    model: ['iPhone 15 Pro Max'],
    storage: ['256GB'],
    color: ['Mavi'],
    condition: ['Sıfır', 'Çok iyi']
  },
  user_id: USER_IDS[0] // İlk kullanıcı
}

// ============================================================================
// CREATE LISTING
// ============================================================================

async function createTestListing() {
  try {
    console.log('🚀 Starting test listing creation...\n')

    // 1. Use predefined user ID
    console.log('1️⃣ Using test user...')
    const userId = TEST_LISTING.user_id
    console.log(`✅ User ID: ${userId}\n`)

    // 2. Fetch Unsplash image
    console.log('2️⃣ Fetching Unsplash image...')
    const imageUrl = await fetchUnsplashImage('iphone 15 pro max blue')
    console.log(`✅ Image URL: ${imageUrl}\n`)

    // 3. Get category name (category_path will be auto-generated by triggers)
    console.log('3️⃣ Fetching category...')
    const { data: category, error: categoryError } = await supabase
      .from('categories')
      .select('name')
      .eq('id', TEST_LISTING.category_id)
      .single()

    if (categoryError || !category) {
      console.error('   ❌ Category not found:', TEST_LISTING.category_id)
      console.error('   💡 Make sure category ID 502 exists in database')
      process.exit(1)
    }

    console.log(`   ✅ Category: ${category.name}\n`)

    // 4. Create listing
    console.log('4️⃣ Creating listing...')
    const { data: listing, error: listingError } = await supabase
      .from('listings')
      .insert({
        user_id: userId,
        title: TEST_LISTING.title,
        description: TEST_LISTING.description,
        category: category.name, // Required NOT NULL field
        category_id: TEST_LISTING.category_id,
        // category_path will be auto-generated by database trigger
        budget: TEST_LISTING.budget,
        location: TEST_LISTING.location,
        urgency: TEST_LISTING.urgency,
        contact_preference: TEST_LISTING.contact_preference,
        main_image_url: imageUrl,
        additional_image_urls: [], // Could add more images
        status: 'active', // Auto-approve for testing
        attributes: TEST_LISTING.attributes,
        accept_terms: true
      })
      .select()
      .single()

    if (listingError) {
      console.error('❌ Failed to create listing:', listingError)
      process.exit(1)
    }

    console.log(`✅ Listing created: ${listing.id}\n`)

    // 4. Summary
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log('🎉 TEST LISTING CREATED SUCCESSFULLY!')
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log(`📝 Title: ${listing.title}`)
    console.log(`💰 Budget: ${listing.budget.toLocaleString('tr-TR')}₺`)
    console.log(`📍 Location: ${listing.location}`)
    console.log(`🔗 URL: http://localhost:3000/ilan/${listing.id}`)
    console.log(`🖼️  Image: ${imageUrl}`)
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')

    console.log('📊 Next steps:')
    console.log('1. Check homepage: http://localhost:3000')
    console.log('2. Check listings page: http://localhost:3000/ilanlar')
    console.log('3. Search for "iPhone": http://localhost:3000/ilanlar?q=iphone')
    console.log('4. If successful, run script again to create more listings\n')

  } catch (error) {
    console.error('❌ Unexpected error:', error)
    process.exit(1)
  }
}

// Run
createTestListing()

