config:
  target: 'http://localhost:3002'
  phases:
    # Warm-up phase
    - duration: 30
      arrivalRate: 5
      name: "Warm-up"
    # Ramp-up phase
    - duration: 60
      arrivalRate: 10
      rampTo: 50
      name: "Ramp-up"
    # Sustained load phase
    - duration: 120
      arrivalRate: 50
      name: "Sustained load"
    # Peak load phase
    - duration: 60
      arrivalRate: 100
      name: "Peak load"
    # Cool-down phase
    - duration: 30
      arrivalRate: 10
      name: "Cool-down"
  defaults:
    headers:
      Authorization: "Bearer {{ $processEnvironment.TOKEN }}"
      Content-Type: "application/json"
  plugins:
    metrics-by-endpoint: {}
  ensure:
    p95: 1000  # 95th percentile should be under 1 second
    p99: 2000  # 99th percentile should be under 2 seconds
    maxErrorRate: 0.05  # Max 5% error rate

scenarios:
  # Health check scenario
  - name: "Health Check"
    weight: 10
    flow:
      - get:
          url: "/health"
          capture:
            - json: "$.status"
              as: "health_status"

  # Listings API scenario
  - name: "Listings API"
    weight: 40
    flow:
      - get:
          url: "/api/v1/listings"
          qs:
            page: "{{ $randomInt(1, 10) }}"
            limit: "{{ $randomInt(5, 20) }}"
          capture:
            - json: "$.success"
              as: "listings_success"
      - get:
          url: "/api/v1/listings/{{ $randomString() }}"
          capture:
            - json: "$.success"
              as: "listing_detail_success"

  # Users API scenario
  - name: "Users API"
    weight: 20
    flow:
      - get:
          url: "/api/v1/users"
          qs:
            page: "{{ $randomInt(1, 5) }}"
            limit: "{{ $randomInt(10, 20) }}"
          capture:
            - json: "$.success"
              as: "users_success"

  # Admin Management API scenario
  - name: "Admin Management API"
    weight: 15
    flow:
      - get:
          url: "/api/v1/admin/users"
          qs:
            page: "{{ $randomInt(1, 3) }}"
            limit: "{{ $randomInt(5, 15) }}"
          capture:
            - json: "$.success"
              as: "admin_users_success"

  # Analytics API scenario
  - name: "Analytics API"
    weight: 10
    flow:
      - get:
          url: "/api/v1/analytics/dashboard"
          qs:
            days: "{{ $randomInt(1, 30) }}"
          capture:
            - json: "$.success"
              as: "analytics_success"

  # Performance API scenario
  - name: "Performance API"
    weight: 5
    flow:
      - get:
          url: "/api/v1/performance/db/metrics"
          capture:
            - json: "$.success"
              as: "db_metrics_success"
      - get:
          url: "/api/v1/performance/cache/performance"
          capture:
            - json: "$.success"
              as: "cache_performance_success"
