global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'benalsam-cluster'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Elasticsearch Service
  - job_name: 'elasticsearch-service'
    static_configs:
      - targets: ['host.docker.internal:3006']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Admin Backend (if metrics available)
  - job_name: 'admin-backend'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # RabbitMQ Management
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-management:15672']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health Checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'host.docker.internal:3006'  # ES Service
        - 'host.docker.internal:3002'  # Admin Backend
    metrics_path: '/health/detailed'
    scrape_interval: 30s
    scrape_timeout: 10s
